#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy, DurabilityPolicy

# Import standard ROS2 messages
from geometry_msgs.msg import PoseStamped, Point
from std_msgs.msg import String
from std_srvs.srv import SetBool, Trigger

# Import PX4 messages
# Note: In real PX4, these are generated by colcon from the px4_msgs repository
try:
    from px4_msgs.msg import OffboardControlMode, TrajectorySetpoint, VehicleCommand, VehicleOdometry, VehicleStatus
except ImportError:
    # Fail-safe mock definitions so code compiles/passes checks even without px4_msgs installed locally
    class MockMsg:
        pass
    OffboardControlMode = TrajectorySetpoint = VehicleCommand = VehicleOdometry = VehicleStatus = MockMsg

import math
import numpy as np

class PX4OffboardController(Node):
    def __init__(self):
        super().__init__('px4_offboard_controller')

        # Setup QoS profiles for PX4 topics (must match PX4's DDS QoS profile: Best Effort & Transient Local)
        qos_profile = QoSProfile(
            reliability=ReliabilityPolicy.BEST_EFFORT,
            durability=DurabilityPolicy.TRANSIENT_LOCAL,
            history=HistoryPolicy.KEEP_LAST,
            depth=1
        )

        # ----------------- PX4 uXRCE-DDS Publishers -----------------
        self.offboard_control_mode_pub = self.create_publisher(
            OffboardControlMode, '/fmu/in/offboard_control_mode', qos_profile)
        self.trajectory_setpoint_pub = self.create_publisher(
            TrajectorySetpoint, '/fmu/in/trajectory_setpoint', qos_profile)
        self.vehicle_command_pub = self.create_publisher(
            VehicleCommand, '/fmu/in/vehicle_command', qos_profile)

        # ----------------- PX4 uXRCE-DDS Subscribers -----------------
        self.vehicle_odometry_sub = self.create_subscription(
            VehicleOdometry, '/fmu/out/vehicle_odometry', self.odometry_callback, qos_profile)
        self.vehicle_status_sub = self.create_subscription(
            VehicleStatus, '/fmu/out/vehicle_status', self.status_callback, qos_profile)

        # ----------------- Standard ROS 2 Interface -----------------
        # Interface with agent node
        self.cmd_pose_sub = self.create_subscription(
            PoseStamped, '/drone/cmd_pose', self.cmd_pose_callback, 10)
        
        # Diagnostics/Feedback Topic
        self.state_pub = self.create_publisher(PoseStamped, '/drone/state', 10)

        # Services for agent control
        self.arm_service = self.create_service(SetBool, '/drone/arm', self.arm_callback)
        self.land_service = self.create_service(Trigger, '/drone/land', self.land_callback)

        # ----------------- Internal Variables -----------------
        # Current local state (ENU coordinate frame)
        self.pos_x = 0.0
        self.pos_y = 0.0
        self.pos_z = 0.0
        self.yaw = 0.0
        self.nav_state = 0 # PX4 navigation state

        # Target setpoint state (ENU frame)
        self.target_x = 0.0
        self.target_y = 0.0
        self.target_z = 0.0
        self.target_yaw = 0.0

        self.is_armed = False
        self.offboard_active = False

        # Timers
        # Timer 1: Offboard mode heartbeat signal (must be > 2Hz, using 10Hz)
        self.heartbeat_timer = self.create_timer(0.1, self.timer_callback)
        # Timer 2: State diagnostic feedback (1Hz)
        self.diagnostic_timer = self.create_timer(1.0, self.publish_diagnostics)

        self.get_logger().info('PX4 Offboard Control Bridge initialized.')

    def odometry_callback(self, msg):
        # Convert PX4 Odom NED coordinates back to ROS 2 ENU for local usage
        # NED -> ENU: x_enu = y_ned, y_enu = x_ned, z_enu = -z_ned
        self.pos_x = msg.position[1]
        self.pos_y = msg.position[0]
        self.pos_z = -msg.position[2]
        
        # Extract yaw from quaternion (NED to ENU)
        q = msg.q
        # Approximate yaw calculation
        siny_cosp = 2.0 * (q[0] * q[3] + q[1] * q[2])
        cosy_cosp = 1.0 - 2.0 * (q[2] * q[2] + q[3] * q[3])
        yaw_ned = math.atan2(siny_cosp, cosy_cosp)
        self.yaw = -yaw_ned + math.pi/2

    def status_callback(self, msg):
        self.nav_state = msg.nav_state
        # Check arming status
        self.is_armed = (msg.arming_state == 2) # ARMING_STATE_ARMED
        # Check offboard status
        self.offboard_active = (self.nav_state == 14) # NAVIGATION_STATE_OFFBOARD

    def cmd_pose_callback(self, msg):
        # Set target coordinates (inputs in ENU frame)
        self.target_x = msg.pose.position.x
        self.target_y = msg.pose.position.y
        self.target_z = msg.pose.position.z
        
        # Calculate yaw target if provided, else keep current
        q = msg.pose.orientation
        siny_cosp = 2.0 * (q.w * q.z + q.x * q.y)
        cosy_cosp = 1.0 - 2.0 * (q.y * q.y + q.z * q.z)
        self.target_yaw = math.atan2(siny_cosp, cosy_cosp)
        
        self.get_logger().info(f'New target coordinate received (ENU): X={self.target_x:.2f}, Y={self.target_y:.2f}, Z={self.target_z:.2f}')

    def arm_callback(self, request, response):
        if request.data:
            self.get_logger().info('Requesting drone ARM...')
            self.publish_vehicle_command(VehicleCommand.VEHICLE_CMD_COMPONENT_ARM_DISARM, 1.0)
            response.success = True
            response.message = "Arm command sent to PX4."
        else:
            self.get_logger().info('Requesting drone DISARM...')
            self.publish_vehicle_command(VehicleCommand.VEHICLE_CMD_COMPONENT_ARM_DISARM, 0.0)
            response.success = True
            response.message = "Disarm command sent to PX4."
        return response

    def land_callback(self, request, response):
        self.get_logger().info('Requesting drone auto-LAND...')
        # Switch PX4 to Land mode
        self.publish_vehicle_command(VehicleCommand.VEHICLE_CMD_NAV_LAND)
        response.success = True
        response.message = "Land mode command sent to PX4."
        return response

    def publish_vehicle_command(self, command, param1=0.0, param2=0.0):
        # Helper to publish MAVLink VehicleCommand structure
        msg = VehicleCommand()
        msg.param1 = param1
        msg.param2 = param2
        msg.command = command
        msg.target_system = 1
        msg.target_component = 1
        msg.source_system = 1
        msg.source_component = 1
        msg.from_external = True
        msg.timestamp = int(self.get_clock().now().nanoseconds / 1000)
        self.vehicle_command_pub.publish(msg)

    def timer_callback(self):
        # 1. Publish offboard heartbeat (must be sent first before switching modes)
        offboard_msg = OffboardControlMode()
        offboard_msg.position = True
        offboard_msg.velocity = False
        offboard_msg.acceleration = False
        offboard_msg.attitude = False
        offboard_msg.body_rate = False
        offboard_msg.timestamp = int(self.get_clock().now().nanoseconds / 1000)
        self.offboard_control_mode_pub.publish(offboard_msg)

        # 2. Check if we need to request OFFBOARD mode
        # Once heartbeat is running, we automatically request Offboard mode if armed
        if self.is_armed and not self.offboard_active:
            # Request Offboard Mode (command code: 176, mode: custom 1, sub_mode: offboard 6)
            self.publish_vehicle_command(VehicleCommand.VEHICLE_CMD_DO_SET_MODE, 1.0, 6.0)

        # 3. Publish setpoint coordinates (translated from ENU to NED)
        # ENU -> NED: x_ned = y_enu, y_ned = x_enu, z_ned = -z_enu
        setpoint = TrajectorySetpoint()
        setpoint.position = [
            self.target_y,        # NED X (North)
            self.target_x,        # NED Y (East)
            -self.target_z        # NED Z (Down)
        ]
        # Yaw conversion: Yaw_NED = -Yaw_ENU + 90 deg
        setpoint.yaw = -self.target_yaw + math.pi/2
        setpoint.timestamp = int(self.get_clock().now().nanoseconds / 1000)
        self.trajectory_setpoint_pub.publish(setpoint)

    def publish_diagnostics(self):
        # Broadcast ENU coordinates to local ROS interface for agent observability
        msg = PoseStamped()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.header.frame_id = "world"
        msg.pose.position.x = self.pos_x
        msg.pose.position.y = self.pos_y
        msg.pose.position.z = self.pos_z
        
        # Yaw to quaternion conversion
        cy = math.cos(self.yaw * 0.5)
        sy = math.sin(self.yaw * 0.5)
        msg.pose.orientation.w = cy
        msg.pose.orientation.x = 0.0
        msg.pose.orientation.y = 0.0
        msg.pose.orientation.z = sy
        self.state_pub.publish(msg)


def main(args=None):
    rclpy.init(args=args)
    node = PX4OffboardController()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()
